# Site settings
title: 蔬菜大王
SEOTitle: Julian's blog
header-img: img/home-bg-geek.jpg
email: azurychu27@gmail.com
description: "我是天空里的一片云"
keyword: "Julian"
url: "http://azurychu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/azurychu/azurychu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "one loves the sunset when one is so sad."
sidebar-avatar: /img/jc_photo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     暂无
#zhihu_username:     jcjc
github_username:    azurychu
#facebook_username:  暂无
#jianshu_username:   暂无
twitter_username:   azurychu27




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID:                             #生成的clientID
  clientSecret:     #生成的clientSecret
  repo: azurychu.github.io    #仓库名称
  owner: azurychu    #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id: G-NLM6M1PZLJ            # Format: UA-xxxxxx-xx
ga_domain: veg27.me                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Twitter",
        href: "https://twitter.com/azurychu27"
    }
]
